name: CI

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      # Build Docker image (tagged latest)
      - name: Build image
        run: docker build -t discord-speech-bot:latest .

      # Install Railway CLI
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      # Login to Railway
      - name: Railway login
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      # Upload & deploy image
      - name: Deploy to Railway
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_ID }} --detached

